# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

future: false 
title: Rupesh Tiwari - Founder of Fullstack Master
email: rupesh.tiwari.info@gmail.com
url: https://www.rupeshtiwari.com
description: >-
  Rupesh is a world renowned Senior Software Architect & Trainer. Expert on Service-Oriented Architecture and Domain-Driven Design & Web Development. Make your next project a success or save a late project.
twitter_username: rupeshtiwari_co
github_username: rupeshtiwari
minimal_mistakes_skin: default
masthead_title: 'Rupesh Tiwari'
subtitle: 'Sr. Software Architect, Author & Trainer'
baseurl: ''
og_image: '/assets/images/bio-photo.jpg'
search: true
repository: 'rupeshtiwari/rupeshtiwari.github.io'
# Build settings
markdown: kramdown
remote_theme: 'mmistakes/minimal-mistakes@4.22.0'

# Outputting
permalink: /:categories/:title/
paginate: # amount of posts to show
paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: 'Rupesh Tiwari'
  avatar: '/assets/images/bio-photo.jpg'
  bio: 'I help students and professionals to become Full Stack Software Developer in less than a year!'
  links:
    - label: 'Email'
      icon: 'fas fa-fw fa-envelope-square'
      url: 'rupesh.tiwari.info@gmail.com'
    - label: 'Blogs'
      icon: 'fa fa-th-large'
      url: '/posts/'
    - label: 'Medium'
      icon: 'fab fa-medium'
      url: 'https://rupesh-tiwari.medium.com/'
    - label: 'Dev.to'
      icon: 'fab fa-dev'
      url: 'https://dev.to/rupeshtiwari'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'http://github.com/rupeshtiwari'
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/rupesh-tiwari'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'http://twitter.com/rupeshtiwari_co'
    - label: 'Facebook'
      icon: 'fab fa-fw fa-facebook-square'
      url: 'https://www.facebook.com/fullstackmaster1'
    - label: 'Angular Training'
      icon: 'fas fa-graduation-cap'
      url: 'https://www.fullstackmaster.net'

footer:
  links:
    - label: 'Blogs for Developers'
      icon: 'fas fa-registered'
      url: 'https://www.rupeshtiwari.com/posts'
    - label: 'Facebook'
      icon: 'fab fa-fw fa-facebook-square'
      url: 'https://www.facebook.com/fullstackmaster1'
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/rupesh-tiwari'
    - label: 'Learn Angular'
      icon: 'fab fa-angular'
      url: 'https://fullstackmaster.net/course/3/mastering-meanjs'
    - label: 'Become Software Developer Free'
      icon: 'fas fa-crown'
      url: 'https://github.com/rupeshtiwari#javascript-for-beginners-client-side'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'http://github.com/rupeshtiwari'
    - label: 'Medium'
      icon: 'fab fa-medium'
      url: 'https://rupesh-tiwari.medium.com/'
    - label: 'Dev.to'
      icon: 'fab fa-dev'
      url: 'https://dev.to/rupeshtiwari'
    - label: 'Fullstack Master'
      icon: 'fas fa-graduation-cap'
      url: 'https://www.fullstackmaster.net'


defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

teaser: '/assets/images/teaser.png'

comments:
  provider: 'disqus'
  disqus:
    shortname: 'https-rupeshtiwari-github-io-1'

analytics:
  provider: 'google-gtag'
  google:
    tracking_id: 'UA-128916623-7'
    anonymize_ip: false # default

bing_site_verification: 8BC08291167B3E15CC4FCC21C5895052

# Social Sharing
twitter:
  username: rupeshtiwari_co

facebook:
  app_id: 421181512329379
  publisher: https://www.facebook.com/fullstackmaster1

breadcrumbs: true

## Personal Configs
jekyll_compose:
  auto_open: true
  default_front_matter:
    posts:
      description:
      author_profile: true
      published: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      image: 'https://i.imgur.com/qxXxmBa.png'
      header:
        image: 'https://i.imgur.com/zipiW93.png'
        teaser: 'https://i.imgur.com/qxXxmBa.png'
        og_image: 'https://i.imgur.com/qxXxmBa.png'
      tags:
        - webdev
        - tutorial
        - beginners


