name: Build & Deploy Github Pages Everyday

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * *"  # runs once daily

jobs:
  build_every_day:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Build site at Docs dir
        run: |
          rm -rf .bundle
          rm -rf Gemfile.lock
          bundle install --no-deployment
          bundle exec jekyll build -d docs

      - name: copy cname
        run: cp CNAME docs

      - name: Commit files
        run: |
          git config --local user.email "RupeshTiwari+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add .
          git commit -m 'update blogs' || echo "No changes"
          git push

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job result
          to: roopkt@gmail.com
          from: Rupesh+GitHubActions@rupesh.com
          secure: true
          body: Build job of ${{ github.repository }} completed successfully!
          reply_to: roopkt@gmail.com
          priority: low
